import { useState } from 'react'
import { Box, Fab } from '@mui/material'
import AddIcon from '@mui/icons-material/Add'
import { RecipeCard } from '@/components/RecipeCard'
import { Recipe } from '@/types/Recipe'

const initialRecipe = {
  id: 1,
  title: `New Recipe - 1`,
  description: 'A description',
}

export const Recipes = () => {
  const [recipes, setRecipes] = useState<Recipe[]>([initialRecipe])

  const addRecipe = () => {
    setRecipes((prevState) => [
      ...prevState,
      {
        id: new Date().getTime(), // In a real scenario you would let the id be generated by the backend / database.
        title: `New Recipe - ${prevState.length + 1}`,
        description: 'A description',
      },
    ])
  }

  const deleteRecipe = (id: number) => {
    setRecipes((prevState) => prevState.filter((recipe) => recipe.id !== id))
  }

  return (
    <>
      <Fab
        color="primary"
        sx={{ position: 'absolute', bottom: 16, right: 16 }}
        onClick={addRecipe}
        data-cy="add-recipe"
      >
        <AddIcon />
      </Fab>
      <Box display="flex" flexWrap="wrap" gap={2}>
        {recipes.map((x) => (
          <RecipeCard
            key={x.id}
            recipe={x}
            deleteRecipe={() => deleteRecipe(x.id)}
          />
        ))}
      </Box>
    </>
  )
}
